apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: payment-gateway

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: payment-gateway
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fineract-apps
