apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: self-service-app

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: self-service-app
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: fineract-apps
