apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-registration
  labels:
    app: customer-registration
    app.kubernetes.io/name: customer-registration
    app.kubernetes.io/component: backend
